### ISSUE TITLE
Integration error: Integration 'aerogarden' not found

### ISSUE THREAD

**Issue by d1cey1** [jacobdonenfeld/homeassistant-aerogarden#23]
Followed the documentation and added all the files necessary into config/custom_components/aerogarden. I have no issues with configuration and then restart. As soon as I add the username and password to configuration.yaml I get the "Integration error: aerogarden - Integration 'aerogarden' not found." Copied the code directly from document with the appropriate information filled in.

`aerogarden:
    username: [EMAIL]
    password: [PASSWORD]`

Is there an adjustment I need to make somewhere or some version incompatibility? I did verify that there's a version key in the manifest log.

Log output 
`ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'aerogarden' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by kuro6** [comment]
I got this error, too. I ended up doing the following:

1. Remove anything related to Aerogarden in the configuration.yaml
2. Once you've copied the files per the instructions, restart HA
3. Open HACS and search for the Aerogarden integration
4. Install via HACS
